### ISSUE TITLE
用油猴会出现跨域问题

### ISSUE THREAD

**Issue by adm1in** [R0A1NG/Botgate_bypass#1]
![图片](https://github.com/R0A1NG/Botgate_bypass/assets/37677854/25f27bf5-61f5-4de6-9428-407e32ccdd77)

**Comment by R0A1NG** [comment]
跨域应该是你的请求域名和js执行位置的域名不同域吧

**Comment by adm1in** [comment]
应该是相同的，我还把脚本开了全局域名应用，┭┮﹏┭┮
![图片](https://github.com/R0A1NG/Botgate_bypass/assets/37677854/f279a9f5-2303-4489-88be-dc009f7411db)

**Comment by adm1in** [comment]
f12控制台运行代码不会出现这个问题

**Comment by R0A1NG** [comment]
> 应该是相同的，我还把脚本开了全局域名应用，┭┮﹏┭┮ ![图片](https://private-user-images.githubusercontent.com/37677854/322379787-f279a9f5-2303-4489-88be-dc009f7411db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNjQ0MjYsIm5iZiI6MTcxMzE2NDEyNiwicGF0aCI6Ii8zNzY3Nzg1NC8zMjIzNzk3ODctZjI3OWE5ZjUtMjMwMy00NDg5LTg4YmUtZGMwMDlmNzQxMWRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDA2NTUyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkNDQwMjMwMzE4MzJmYjE2YmI3ZmM4ZmZlMzBmOWUwYmZjOGUxZWI1ODliNDVlYzIzYTJmN2NiYmRmZmU5MWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ruV20h_QfzcfEXN4jgFsDZH59NW1nZtuxzxajhCVJH4)

这个不要用全局，在那个站执行就写哪个。写的ws通信只会给最新连接的客户端发消息。油猴写全局的话，其他页面也会加载这个js，可能会覆盖最新ws连接。

**Comment by adm1in** [comment]
可能是我这边网站的问题，感谢作者大大
